### ISSUE TITLE
How to train this code on our own data set.?

### ISSUE THREAD

**Issue by DRAhmadFaraz** [wkentaro/label-fusion#2]
@wkentaro Respected Sir, Can you please guide me how to run this code on our Custom images.

And How to get "frame-0000XX.pose.txt" files as an input for this code.??

I will be waiting for your kind responce..

**Comment by wkentaro** [comment]
> How to get "frame-0000XX.pose.txt" files as an input for this code.?

You can correct data with a hand-mounted camera on a robot.

In the example, this repo is using data from this paper:
https://github.com/andyzeng/apc-vision-toolbox
